spring:
  application:
    name: sistema-evento
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eventsystem
    username: root
    password: root

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    sendgrid:
      api:
        key:

  flyway:
    enabled: true
    baseline-on-migrate: true


springdoc:
  swagger-ui:
      path: /docs-event.html
  api-docs:
    path: /docs-event


